name: electron-app
version: '1.0.0'
base: 'core18'
summary: App summary
description: |
  App description
grade: devel
confinement: devmode

parts:
  electron-deps:
    plugin: nil
    stage-packages:
      - libnotify4
      - libnss3
      - libpcre3
      - libuuid1
      - libxss1
      - libxtst6
